// ─────────────────────────────────────────────────────────────────────────────
// File: frontend/src/types/index.ts
// Purpose: All shared TypeScript types for the application.
//          Single source of truth — components, hooks, and services import from here.
// ─────────────────────────────────────────────────────────────────────────────

// ── Graph types ───────────────────────────────────────────────────────────────
// Schema modelled on the C4 model (https://c4model.com/diagrams/notation):
//   - Every element carries: name, type, technology, description
//   - Every relationship carries: label (specific verb phrase), technology, direction
//   - Edges are always unidirectional; sync/async encoded visually (solid vs dashed)
//
// Node types map to system-design primitives:
//   client     — external actors: users, browsers, mobile apps
//   service    — processing logic: APIs, microservices, ML models, workers
//   datastore  — persistent state: databases, caches, vector stores, queues, S3
//   gateway    — traffic entry / control: load balancers, API gateways, CDN
//   network    — boundaries & plumbing: VPC, subnet, NAT, firewall, VPC endpoint
//   external   — third-party dependencies: SaaS APIs, managed services
//   control    — policy/security enforcement: access control, guardrails, filters, validators
//   decision   — non-service constraints or choices: budgets, approval gates, routing decisions

export type NodeType =
  | 'client'
  | 'service'
  | 'datastore'
  | 'gateway'
  | 'network'
  | 'external'
  | 'control'
  | 'decision';

export interface GraphNode {
  id: string;
  label: string;              // max 3 words / 20 chars display name
  type: NodeType;             // functional role in the architecture
  technology: string;         // specific tech choice, e.g. "Python / FastAPI", "PostgreSQL 15"
  description: string;        // 1-sentence responsibility summary (generated by graph worker)
  tier?: 'public' | 'private'; // network accessibility — omitted for concept graphs
  lane?: 'main' | 'bottom';  // vertical swim lane: main (default) or bottom (observability/monitoring)
  detail: string | null;      // enriched book content (Node Detail Worker, async)
  book_refs?: string[];       // book citations (Node Detail Worker, async)
  layer?: 'concept' | 'architecture';
  canonical_id?: string;
  confidence?: number;
  evidence_chunk_ids?: string[];
  design_origin?: 'applied';
}

export interface GraphEdge {
  source: string;
  target: string;
  label: string;              // specific action phrase: "sends query", "streams embeddings"
  technology: string;         // transport + format: "HTTPS/JSON", "gRPC/Protobuf", "Kafka"
  sync: 'sync' | 'async';    // solid line = sync, dashed line = async
  description: string;        // 1 sentence: what data flows over this connection
  type?: 'loop';              // loop = hidden feedback arc, revealed on hover of source node
  edge_id?: string;
  relation?: string;
  confidence?: number;
  supporting_chunk_ids?: string[];
}

export interface GraphStep {
  step: number;
  nodes: string[];         // node IDs active at this step
  description: string;
}

export interface GraphGroup {
  id: string;
  label: string;        // e.g. "Orchestration Layer"
  nodeIds: string[];    // IDs of member nodes
}

export interface GraphViewState {
  nodePositions: Record<string, { x: number; y: number }>;
  viewport: {
    x: number;
    y: number;
    k: number;
  };
}

export interface GraphData {
  graph_type: 'architecture' | 'concept';
  title: string;
  nodes: GraphNode[];
  edges: GraphEdge[];
  sequence: GraphStep[];
  groups?: GraphGroup[];
  version?: string;
  design_origin?: 'applied';
  resolved_complexity?: ComplexityLevel;
  assumptions?: string[];
  view_state?: GraphViewState;
}

// ── Chat types ────────────────────────────────────────────────────────────────

export type MessageRole = 'user' | 'assistant';

export interface Message {
  id: string;
  role: MessageRole;
  content: string;
  isStreaming?: boolean;   // true while response_delta events are arriving
  kind?: 'text' | 'explanation';
  title?: string;
  relatedNodeIds?: string[];
}

export interface ThreadSummary {
  id: string;
  title: string;
  created_at: string;
  updated_at: string;
  last_seen_at: string;
}

export interface ThreadDetail {
  thread: {
    id: string;
    title: string;
    graph_data: GraphData | null;
    created_at: string;
    updated_at: string;
    last_seen_at: string;
  };
  messages: Array<{
    id: string;
    role: MessageRole;
    content: string;
    created_at: string;
  }>;
}

export interface AuthUser {
  id: string;
  email: string;
}

export interface AuthSession {
  access_token: string;
  refresh_token: string;
  expires_in?: number;
  token_type?: string;
  user: AuthUser;
}

// ── Streamed server event types — Server → Browser ────────────────────────────

export interface WorkerStatusEvent {
  type: 'worker_status';
  worker: 'orchestrator' | 'rag' | 'graph' | 'critic' | 'research';
  status: string;
}

export interface ThinkingDeltaEvent {
  type: 'thinking_delta';
  content: string;
}

export interface ResponseDeltaEvent {
  type: 'response_delta';
  content: string;
}

export interface GraphDataEvent {
  type: 'graph_data';
  data: GraphData;
}

export interface GraphCandidateEvent {
  type: 'graph_candidate';
  evaluation_id: string;
  graph_version?: string | null;
  data: GraphData;
}

export type WorkflowPhase =
  | 'evidence'
  | 'architect'
  | 'challenger'
  | 'integrate'
  | 'render'
  | 'review'
  | 'explain';

export interface WorkflowProgressEvent {
  type: 'workflow_progress';
  phase: WorkflowPhase;
  status: 'active' | 'complete' | 'retry' | 'rejected';
  title: string;
  detail: string;
}

export interface ExplanationBlockEvent {
  type: 'explanation_block';
  block_id: string;
  title: string;
  content: string;
  related_node_ids: string[];
  evidence_refs: string[];
  graph_version?: string | null;
}

export interface NodeDetailEvent {
  type: 'node_detail';
  node_id: string;
  description: string;
  book_refs: string[];
  graph_version?: string | null;
}

export interface SuggestedQuestionsEvent {
  type: 'suggested_questions';
  questions: string[];
}

export interface RetrievalNoticeEvent {
  type: 'retrieval_notice';
  request_id: string;
  message: string;
}

export interface GraphNoticeEvent {
  type: 'graph_notice';
  message: string;
}

export interface DoneEvent {
  type: 'done';
}

export interface ErrorEvent {
  type: 'error';
  content: string;
}

export interface ProviderSwitchEvent {
  type: 'provider_switch';
  provider: string;   // e.g. "openai" — signals Claude is unavailable, GPT is responding
}

export interface ResponseResetEvent {
  type: 'response_reset';
}

export interface SteerAppliedEvent {
  type: 'steer_applied';
  content: string;
  steer_count: number;
}

export interface CommandRejectedEvent {
  type: 'command_rejected';
  reason: string;
}

export interface StoppedEvent {
  type: 'stopped';
}

export type ServerEvent =
  | WorkerStatusEvent
  | ThinkingDeltaEvent
  | ResponseDeltaEvent
  | GraphDataEvent
  | GraphCandidateEvent
  | WorkflowProgressEvent
  | ExplanationBlockEvent
  | NodeDetailEvent
  | SuggestedQuestionsEvent
  | RetrievalNoticeEvent
  | GraphNoticeEvent
  | DoneEvent
  | ErrorEvent
  | ProviderSwitchEvent
  | ResponseResetEvent
  | SteerAppliedEvent
  | CommandRejectedEvent
  | StoppedEvent;

// ── Request payload event types — Browser → Server ────────────────────────────

export interface SendMessageEvent {
  type: 'message';
  content: string;
}

export interface NodeSelectedEvent {
  type: 'node_selected';
  node_id: string;
  title: string;
  description: string;
}

export type ClientEvent = SendMessageEvent | NodeSelectedEvent;

// ── Mode control types ────────────────────────────────────────────────────────

// Controls how many nodes the graph worker generates
export type ComplexityLevel = 'auto' | 'low' | 'prototype' | 'production';

// Controls whether the graph worker runs each turn
export type GraphMode = 'auto' | 'on' | 'off';

// ── UI state ──────────────────────────────────────────────────────────────────

export interface WorkerStatus {
  rag: string | null;
  graph: string | null;
  critic: string | null;
  orchestrator: string | null;
  research: string | null;
}

export interface SelectedNode {
  node: GraphNode;
  suggestions: string[];
}

export interface RetrievalNotice {
  requestId: string;
  message: string;
  requested: boolean;
}

export interface GraphNotice {
  message: string;
}

export interface GraphCandidate {
  evaluationId: string;
  graphVersion?: string | null;
  data: GraphData;
}

export interface WorkflowProgress {
  phase: WorkflowPhase;
  status: 'active' | 'complete' | 'retry' | 'rejected';
  title: string;
  detail: string;
}

export interface DiagramLayoutReport {
  viewport_width: number;
  viewport_height: number;
  rendered_nodes: number;
  rendered_edges: number;
  overlap_count: number;
  clipped_nodes: number;
  minimum_text_px: number;
  capture_error?: string;
}

// ── Analytics / dashboard ───────────────────────────────────────────────────

export type AnalyticsEventName =
  | 'auth_viewed'
  | 'otp_requested'
  | 'otp_verified'
  | 'google_signin_started'
  | 'prepare_clicked'
  | 'prepare_succeeded'
  | 'prepare_failed'
  | 'thread_created'
  | 'thread_selected'
  | 'thread_deleted'
  | 'chat_sent'
  | 'chat_stream_started'
  | 'chat_stream_completed'
  | 'chat_stream_failed'
  | 'chat_stopped'
  | 'node_selected'
  | 'expand_graph_clicked'
  | 'search_tool_requested'
  | 'mode_changed';

export interface AnalyticsEventProperties {
  thread_id?: string;
  client_request_id?: string;
  complexity?: ComplexityLevel;
  graph_mode?: GraphMode;
  research_enabled?: boolean;
  backend_readiness_state?: string;
  has_selected_text_context?: boolean;
  provider_notice_shown?: boolean;
  error_code?: string;
  node_id?: string;
  node_label?: string;
  mode?: string;
  value?: string | number | boolean;
  request_id?: string;
}

export interface DashboardOverviewResponse {
  window_hours: number;
  kpis: {
    dau: number;
    wau: number;
    prepares: number;
    chats_sent: number;
    chats_completed: number;
    chats_failed: number;
    stop_rate: number;
    search_tool_request_rate: number;
    avg_chat_latency_ms: number | null;
  };
  providers: Record<string, number>;
}

export interface DashboardTrendPoint {
  start_epoch: number;
  label: string;
  chat_sent: number;
  chat_completed: number;
  chat_failed: number;
  avg_chat_latency_ms: number | null;
  completion_rate: number;
  provider_usage: Record<string, number>;
}

export interface DashboardTrendsResponse {
  bucket: 'day' | 'hour';
  points: DashboardTrendPoint[];
}

export interface DashboardFunnelStep {
  event_type: string;
  actors: number;
  conversion_from_previous: number | null;
}

export interface DashboardFunnelResponse {
  window_days: number;
  steps: DashboardFunnelStep[];
}

export interface DashboardRequestRow {
  path?: string;
  status_code?: number;
  latency_ms?: number;
  created_at_epoch: number;
  request_id?: string | null;
  trace_id?: string | null;
  client_request_id?: string | null;
}

export interface DashboardModeBreakdown {
  label: string;
  count: number;
}

export interface DashboardFallbackRow {
  operation: string;
  provider: string;
  model: string;
  created_at_epoch: number;
  duration_ms?: number;
  request_id?: string | null;
  trace_id?: string | null;
}

export interface DashboardFailuresResponse {
  recent_failed_requests: DashboardRequestRow[];
  slow_requests: DashboardRequestRow[];
  provider_fallbacks: DashboardFallbackRow[];
  most_used_modes: DashboardModeBreakdown[];
}

export interface DashboardLLMOperation {
  operation: string;
  provider: string;
  model: string;
  calls: number;
  avg_duration_ms: number;
  fallback_rate: number;
  error_rate: number;
}

export interface DashboardLLMPerformanceResponse {
  operations: DashboardLLMOperation[];
  recent_fallbacks: DashboardFallbackRow[];
}
